#!/bin/bash
#==============================================================================
#TITLE:            blacklist
#DESCRIPTION:      This script was build to provide reporting/monitoring of IP/Domain in public blacklist
#AUTHOR:           Louis Ouellet
#DATE:             2020-07-18
#VERSION:          1.1-1

#==============================================================================
# BASH SETUP
#==============================================================================

# Initialize Timer
SECOND=0

# Script name
scriptname=$(echo $0 | sed -e 's@.*/@@')

# Script Personalisation
Title=""
help_options="
-v                     => Enable Reporting Mode
                          Input commands sent are stored in ${logs_file}
-e                     => Compile errors and warnings after execution
-s                     => Send report via email
-f                     => Disable all formatting
"
help_functions="
"

# Set Bash
set -o pipefail

# SETS LOCALE
# Updated to en_US to support
#export LC_ALL=en_US.UTF-8 > /dev/null 2>&1 || export LC_ALL=en_GB.UTF-8 > /dev/null 2>&1 || export LC_ALL=C.UTF-8 > /dev/null 2>&1

#==============================================================================
# GATHERING SYSTEM INFORMATION
#==============================================================================

# Identify OS
unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     OS=Linux;;
    Darwin*)    OS=Mac;;
    CYGWIN*)    OS=Cygwin;;
    MINGW*)     OS=MinGw;;
    *)          OS="UNKNOWN:${unameOut}"
esac

# Identify Distribution
case $OS in
  Linux)
    Distribution=$(hostnamectl | grep 'Operating System' | cut -d: -f2 | xargs)
    Architecture=$(hostnamectl | grep 'Architecture' | cut -d: -f2 | xargs)
    PackageManager=
    if [[ "$(whereis pacman | awk '{ print $2 }')" != '' ]]; then PackageManager="pacman"; fi
    if [[ "$(whereis yum | awk '{ print $2 }')" != '' ]]; then PackageManager="yum"; fi
    if [[ "$(whereis dnf | awk '{ print $2 }')" != '' ]]; then PackageManager="dnf"; fi
    if [[ "$(whereis apt-get | awk '{ print $2 }')" != '' ]]; then PackageManager="apt-get"; fi
    # if [[ "$(whereis emerge | awk '{ print $2 }')" != '' ]]; then PackageManager="emerge"; fi
    # if [[ "$(whereis zypp | awk '{ print $2 }')" != '' ]]; then PackageManager="zypp"; fi
    ;;
  *);;
esac

#==============================================================================
# FORMATTING
#==============================================================================

function format(){
    # COLORS
    blackText=$(tput setaf 0)   # Black
    redText=$(tput setaf 1)     # Red
    greenText=$(tput setaf 2)   # Green
    yellowText=$(tput setaf 3)  # Yellow
    blueText=$(tput setaf 4)    # Blue
    magentaText=$(tput setaf 5) # Magenta
    cyanText=$(tput setaf 6)    # Cyan
    whiteText=$(tput setaf 7)   # White
    resetText=$(tput sgr0)      # Reset to default color

    # STYLES
    boldText=$(tput bold)
    blinkingText=$(tput blink)
    dimText=$(tput dim)
}

function clrformat(){
    # COLORS
    blackText=
    redText=
    greenText=
    yellowText=
    blueText=
    magentaText=
    cyanText=
    whiteText=
    resetText=

    # STYLES
    boldText=
    blinkingText=
    dimText=
}

#==============================================================================
# Elements
#==============================================================================

function elements(){
    # CHECK BOXES
    checkBoxGood="[${greenText}✓${resetText}]"       # Good
    checkBoxBad="[${redText}✗${resetText}]"          # Bad
    checkBoxQuestion="[${magentaText}?${resetText}]"  # Question / ?
    checkBoxInfo="[${cyanText}i${resetText}]"      # Info / i
    checkBoxOutput="[${yellowText}!${resetText}]"      # Output / !

    # Current Date & Time
    PDATE(){
	    printf "[$(date '+%Y-%m-%d %H:%M:%S')]"
    }

    # Log Types
    INFO=$checkBoxInfo
    OUTPUT=$checkBoxOutput
    SUCCESS=$checkBoxGood
    ERROR=$checkBoxBad
    WARNING=$checkBoxOutput

    # Log Actions
    CHECK="[CHECK]"
    START="[START]"
    TIMED="[TIMED]"
    RUN="[ RUN ]"
    EMPT="[     ]"
    OUT="[ OUT ]"
    VAR="[ VAR ]"
}

#==============================================================================
# HELPERS
#==============================================================================

function help(){
  if [ "$DEBUG" = "true" ]; then
    echo "Help" | dbg i s
  fi
  echo -e "
Usage: ./$scriptname [options] IP/FQDN

Options:
$help_options
"
}

function error(){
  printf "FATAL ERROR: $1\n"
  help
  exit 0
}

function dbg(){
  if [ "$1" != "" ] && [ "$2" != "" ]; then
    case "$1" in
      info|i)
        TYPE=$INFO
        ;;
      success|s)
        TYPE=$SUCCESS
        ;;
      error|e)
        TYPE=$ERROR
        ;;
      output|o)
        TYPE=$OUTPUT
        ;;
      warning|w)
        TYPE=$WARNING
        ;;
      question|q)
        TYPE=$checkBoxQuestion
        ;;
    esac
    case "$2" in
      check|c|test|t)
        ACTION=$CHECK
        ;;
      start|s)
        ACTION=$START
        ;;
      run|r)
        ACTION=$RUN
        ;;
      empty|e)
        ACTION=$EMPT
        ;;
      output|o)
        ACTION=$OUT
        ;;
      timed|t)
        ACTION=$TIMED
        ;;
      variable|var|v)
        ACTION=$VAR
        ;;
    esac
    while read DCMD; do
      if [ "$3" != "" ]; then
        LogFile=$3
      fi
			DCMDout=$(echo $DCMD | sed -e "s/\n/ /g")
			for string in ${protect[@]};do
				DCMDout=$(echo $DCMDout | sed -e "s/$string/xxx/g")
			done
      if [ "$DEBUG" = "true" ]; then
        printf "${TYPE}$(PDATE)${ACTION} ${DCMDout}\n" | tee -a $logs_file
      else
        printf "${TYPE}$(PDATE)${ACTION} ${DCMDout}\n"
      fi
    done
  else
    error "Missing Argument(s)"
  fi
}

function exec(){
  if [ "$1" != "" ]; then
    echo "exec $1" | dbg i s
    if eval $1 2>&1 | dbg o o;then
      echo "$1" | dbg s r
    else
      echo "$1" | dbg e r
    fi
  else
    error "Missing Argument(s)"
  fi
}

function pkg(){
  if [ "$1" != "" ]; then
    if [ "$DEBUG" = "true" ]; then
      echo "pkg $1" | dbg i s
    fi
    case $OS in
      Linux)
        if [[ "$(whereis $1 | awk '{ print $2 }')" == '' ]]; then
          case $PackageManager in
            pacman)
              exec "sudo pacman -S --noconfirm $1"
              ;;
            dnf)
              exec "sudo dnf install -y $1"
              ;;
            yum)
              exec "sudo yum install -y $1"
              ;;
            apt-get)
              exec "sudo apt-get update"
              exec "sudo apt-get install -y --fix-missing $1"
              ;;
            *)
              echo "Unable to install $1" | dbg e e
              echo "Unsupported Package Manager" | dbg e e
              ;;
          esac
        fi
        ;;
      Mac)
        if [[ "$(command -v $1)" == '' ]]; then
          exec "brew install $1"
        fi
        ;;
      *)
        echo "Unable to install $1" | dbg e e
        echo "Unsupported OS" | dbg e e
        ;;
    esac
  else
    error "Missing Argument(s)"
  fi
}

function send(){
    exec "echo \"$2\" | s-nail -s \"$1\" -S smtp-use-ssl -S ssl-rand-file=/tmp/mail.entropy -S smtp-auth=login -S smtp=\"smtps://${smtp_host}:${smtp_port}\" -S from=\"${send_from}(${send_name})\" -S smtp-auth-user=\"${smtp_username}\" -S smtp-auth-password=\"${smtp_password}\" -S ssl-verify=ignore -a \"$logs_file\" ${send_to}"
}

#==============================================================================
# SETTINGS
#==============================================================================


function protectDCMD(){
	protect=(
		$smtp_host
		$smtp_port
		$smtp_username
		$smtp_password
		$send_name
		$send_from
	)
}

function import(){
  if [[ -f "settings.json" ]]; then
    smtp_host=$(jq -r '.smtp.host' settings.json)
    smtp_port=$(jq -r '.smtp.port' settings.json)
    smtp_username=$(jq -r '.smtp.username' settings.json)
    smtp_password=$(jq -r '.smtp.password' settings.json)
    send_name=$(jq -r '.send.name' settings.json)
    send_from=$(jq -r '.send.from' settings.json)
    send_to=$(jq -r '.send.to' settings.json)
    logs_directory=$(jq -r '.logs.directory' settings.json)
  fi
  blacklists=$(jq -r '.lists[]' list.json)
  case $OS in
    Linux)
      logs_file="${logs_directory}$(date +%s%N).log"
      ;;
    Mac)
      logs_file="${logs_directory}$(date +%s).log"
      ;;
    *);;
  esac
	protectDCMD
}

#==============================================================================
# FUNTIONS
#==============================================================================

function reverse(){
  reverse=$(echo $1 | sed -ne "s~^\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)\.\([0-9]\{1,3\}\)$~\4.\3.\2.\1~p")
  if [ "x${reverse}" = "x" ] ; then
    error $2
  fi
}

function loop(){
    reverse_dns=$(dig +short -x $1)
    echo $1 name ${reverse_dns:----} | dbg i v
    for bl in ${blacklists} ; do
        listed="$(dig +short -t a ${reverse}.${bl})"
        if [[ $listed ]]; then
            if [[ $listed == *"timed out"* ]]; then
                echo "dig +short -t a ${reverse}.${bl} => ${listed}" | dbg w r
            else
                echo "dig +short -t a ${reverse}.${bl} => ${listed}" | dbg e r
            fi
        else
            echo "dig +short -t a ${reverse}.${bl} => ${listed}" | dbg s r
        fi
    done
}

function main(){
  case $OS in
    Linux)
      fqdn=$(echo $1 | grep -P "(?=^.{5,254}$)(^(?:(?!\d+\.)[a-za-z0-9_\-]{1,63}\.?)+(?:[a-za-z]{2,})$)")
      ;;
    Mac)
      fqdn=$(echo $1 | grep -e "(?=^.{5,254}$)(^(?:(?!\d+\.)[a-za-z0-9_\-]{1,63}\.?)+(?:[a-za-z]{2,})$)")
      ;;
    *);;
  esac
  if [[ $fqdn ]] ; then
    domain=$(host $1 | head -n1 | awk '{print $4}')
    reverse $domain "IP not valid or domain could not be resolved."
  else
    reverse $1 "IP not valid."
  fi
  loop $1
}

#==============================================================================
# RUN OPTIONS & FUNCTIONS
#==============================================================================

format
elements

while getopts ":vesf" option
	do
	case "${option}"
		in
			v)
				DEBUG=true
				;;
			e)
				ERRORrpt=true
				;;
			s)
				SENDrpt=true
				;;
			f)
				clrformat
				elements
				;;
			\? )
				echo "Invalid option: $OPTARG" 1>&2
                help
                exit 0
				;;
			: )
				echo "Invalid option: $OPTARG requires an argument" 1>&2
                help
                exit 0
				;;
	esac
done
shift $((OPTIND -1))

#==============================================================================
# RUN SCRIPT
#==============================================================================

pkg jq
pkg s-nail
pkg dig
import
main $1

if [[ "$DEBUG" = "true" ]]; then
  duration=$SECONDS
  echo "#############################################################" | dbg i e
  echo "log file.......: $logs_file" | dbg i v
  echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed." | dbg i v
  echo "#############################################################" | dbg i e
fi

if [[ "$SENDrpt" = "true" ]]; then
  send "IP/FQDN: $1" "Blacklist Scan of $1 was completed. See attached report."
fi

if [[ "$ERRORrpt" = "true" ]]; then
  if [[ -f "$logs_file" ]]; then
    cat $logs_file | egrep "✗|!"
  fi
fi

exit 0
